services:
  tests_host:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      # - "./tests_host/integration-tests:/integration-tests"
      # - "./tests_host/screenshots:/screenshots"
    # command: "wait-for-it.sh react_host_client:3000 && \
    #   -- mocha --recursive /integration-tests"
    working_dir: /app
    command: "sleep infinity"
    ports:
      - 3000:3000
