kind: pipeline
name: deploy_firebase
type: docker

steps:
  - name: deploy_firebase
    image: node:18
    commands:
      - cd docusaurus-dashboard
      - yarn
      - yarn build
      - yarn deploy_firebase
