kind: pipeline
name: hello-alpine
type: docker

steps:
  - name: deploy_firebase
    image: alpine
    commands:
      - cd docusaurus-dashboard
      - yarn
      - yarn build
      - yarn deploy_firebase
