kind: pipeline
name: deploy_firebase
type: docker

steps:
  - name: deploy_firebase
    image: node:18
    commands:
      - cd docusaurus-dashboard
      - yarn
      - yarn build
      - yarn deploy_firebase

  - name: slack-notify
    image: plugins/slack
    secrets: [slack_webhook]
    webhook: $slack_webhook
    channel: your-channel-name
    template: >

      {{#success build.status}} ✔ {{ else }} :x: {{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }} * (type: `{{ build.event }}`)

      Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>

      Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>

      Author: {{ build.author }}      

      Build: <{{ build.link }}| Drone Build {{ build.number }} ↗>

    when:
      status: [success, failure]
      branch: [master, develop]
